### ISSUE TITLE
AttributeError while trying to use

### ISSUE THREAD

**Issue by sagarchalise** [robodair/pydocstring#10]
Got this error  when running `pydocstring`

```
doc_text = pydocstring.generate_docstring(
  File "/usr/local/lib/python3.8/site-packages/pydocstring/__init__.py", line 65, in generate_docstring
    return formatter_module.function_docstring(scope)
  File "/usr/local/lib/python3.8/site-packages/pydocstring/formatters/google.py", line 46, in function_docstring
    *get_return_info(ret, parso_function.annotation))
  File "/usr/local/lib/python3.8/site-packages/pydocstring/formatters/format_utils.py", line 61, in get_return_info
    expression = "".join(x.get_code().strip() for x in ret.children[1:])
AttributeError: 'Keyword' object has no attribute 'children'
```

the generation code is `def report(loan_data, all_amount=False, balance=False):`

Backdrop:
I am trying to build a plugin for [Geany](https://geany.org).
Its [here] (https://github.com/sagarchalise/geany-pycoding/blob/peasy/peasypycoding.py#L416).
Basically, it calls pydocstring on source content.

**Comment by robodair** [comment]
Hey @sagarchalise - Sorry I haven't been keeping an eye on GitHub in quite a while and have stalled on a number of hobby projects. Did you manage to work around this and still use pydocstring, or did you manage to use jedi directly?

**Comment by sagarchalise** [comment]
@robodair 
I opted for my own solution based on `parso` as I was doing some processing after the doc was generating. I did take some cue from your codebase but I am not using `pydocstring`.
